### ISSUE TITLE
sapporo.beam#211

### ISSUE THREAD

**Issue by anandpotukuchi** [sapporo-beam/sapporo-beam#211]
Invite to ElixirConf Asia 2019 

hi guys,

I don't speak Japanese We're putting together an Elixir Conf in asia next year. Can you please fill up the contact form in the link below if you're interested. Keynote speakers include Jose Valim,  creator of Elixir and chris mccord creator of phoenix framework

[https://docs.google.com/forms/d/e/1FAIpQLSf-PaiIyK29nec5v6_nlQRINKeD50d6UXoZyevSO1SizOvZ4w/viewform?usp=sf_link](https://docs.google.com/forms/d/e/1FAIpQLSf-PaiIyK29nec5v6_nlQRINKeD50d6UXoZyevSO1SizOvZ4w/viewform?usp=sf_link)

thanks

**Comment by niku** [comment]
Thank you for the invitation @anandpotukchi.

I had hesitated to input the form due to Address is required.
Could you be it optional or have something a workaround?

thanks

**Comment by anandpotukuchi** [comment]
@niku  I've modified the form - please fill it and send it in.
