### ISSUE TITLE
sapporo.beam#14

### ISSUE THREAD

**Issue by myokoym** [sapporo-beam/sapporo-beam#4]
- 日時 2014-05-29 19:00-21:00
- 場所 [スターバックスコーヒー札幌グランドホテル店](http://www.starbucks.co.jp/store/search/detail.php?id=333)

**Comment by myokoym** [comment]
"Sapporo.beamとはErlangVMを使うプログラミング言語ErlangとかElixirについてワイワイ話すところ．
ElixirのインストールやElixirのドキュメント翻訳やWebフレームワークに触ってみたりできる．"
2014/04/23/Sapporo.beamやる - ヽ（´・肉・｀）ノログ
http://niku.name/articles/2014/04/23/Sapporo.beam%E3%82%84%E3%82%8B

**Comment by niku** [comment]
Thanks a lot! :star:

**Comment by imaz** [comment]
:meat_on_bone:

**Comment by niku** [comment]
今日は [alias，requireとimpot](https://github.com/niku/elixir-lang.github.com/blob/translate-into-japanese-v0.13/getting_started/13.markdown) を翻訳しました
